In [16]:
from tokenization_kbalbert import KbAlbertCharTokenizer
import warnings
warnings.filterwarnings('ignore')

In [26]:
kb_albert_model_path = '/Users/hyebin/Desktop/github/KB/model'

tokenizer = KbAlbertCharTokenizer.from_pretrained(kb_albert_model_path)
query = 'KB새희망홀씨 긴급생계자금에 대해 설명해줘'
print(tokenizer.tokenize(query))

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'AlbertTokenizerFast'. 
The class this function is called from is 'KbAlbertCharTokenizer'.


['K', '##B', '##새', '##희', '##망', '##홀', '##씨', '긴', '##급', '##생', '##계', '##자', '##금', '##에', '대', '##해', '설', '##명', '##해', '##줘']


In [24]:
from transformers import TFAlbertModel

# Load Tokenizer
tokenizer = KbAlbertCharTokenizer.from_pretrained(kb_albert_model_path)

# Load Model from pytorch checkpoint
tf_model = TFAlbertModel.from_pretrained(kb_albert_model_path, from_pt=True)

# inference text input to sentence vector of last layer
text = '방카슈랑스는 금융의 겸업화 추세에 부응하여 금융산업의 선진화를 도모하고 금융소비자의 편익을 위하여 도입되었습니다.'
tf_inputs = tokenizer(text, return_tensors='tf')
print(tf_model(tf_inputs))

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'AlbertTokenizerFast'. 
The class this function is called from is 'KbAlbertCharTokenizer'.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFAlbertModel: ['predictions.dense.bias', 'predictions.LayerNorm.bias', 'predictions.decoder.bias', 'predictions.LayerNorm.weight', 'predictions.decoder.weight', 'sop_classifier.classifier.bias', 'predictions.dense.weight', 'sop_classifier.classifier.weight', 'predictions.bias']
- This IS expected if you are initializing TFAlbertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFAlbertModel from a PyTorch model that you expect to be exactly 

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(1, 54, 768), dtype=float32, numpy=
array([[[-0.24243914, -0.11504207,  0.17393395, ..., -0.1104427 ,
         -0.25206167, -0.23426075],
        [-0.23975652,  0.60240734,  0.21395496, ..., -0.10028092,
         -0.08111619, -0.3386628 ],
        [-0.06281107,  0.17218241, -0.2953688 , ...,  0.02597594,
         -0.12882954, -0.03670276],
        ...,
        [ 0.0405852 , -0.04625406,  0.01750807, ..., -0.00161687,
         -0.06357278,  0.0401556 ],
        [ 0.11111082, -0.21249932,  0.01409133, ...,  0.13796112,
         -0.1251674 , -0.08493054],
        [ 0.04058535, -0.04625037,  0.01748614, ..., -0.00163446,
         -0.06360043,  0.04017929]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 1.19581260e-02, -1.15415768e-03, -9.98579085e-01,
        -1.94304466e-01,  9.99508560e-01, -1.00000000e+00,
         3.82515341e-02,  5.71798980e-02,  5.21148331e-02,
         3.490

In [25]:
tf_outputs = tf_model(tf_inputs)[0]
print(tf_outputs)

tf.Tensor(
[[[-0.24243914 -0.11504207  0.17393395 ... -0.1104427  -0.25206167
   -0.23426075]
  [-0.23975652  0.60240734  0.21395496 ... -0.10028092 -0.08111619
   -0.3386628 ]
  [-0.06281107  0.17218241 -0.2953688  ...  0.02597594 -0.12882954
   -0.03670276]
  ...
  [ 0.0405852  -0.04625406  0.01750807 ... -0.00161687 -0.06357278
    0.0401556 ]
  [ 0.11111082 -0.21249932  0.01409133 ...  0.13796112 -0.1251674
   -0.08493054]
  [ 0.04058535 -0.04625037  0.01748614 ... -0.00163446 -0.06360043
    0.04017929]]], shape=(1, 54, 768), dtype=float32)
